### ISSUE TITLE
Issues raised during release process for 0.3.0

### ISSUE THREAD

**Issue by pcattori** [Datatamer/unify-client-python#47]
- [x] Retag releases without leading `v`
- [x] Consolidate dev deps into `dev-requirements.txt` or `dev` extras (#48)
- [x] Travis CI should publish commits tagged with release version (#49)
- [x] `flake8-import-order` (#50)
- [x] Rewrite RELEASE.md with updated changes (#51)
- [x] Simplify README: replace header links with just links (#52)
- [x] Issue template (#55)
  - make sure this issue doesn't already exist. if it does, consider 👍 existing issue
  - Feature request
  - Bug request
- [x] PR template (#57)
  - docs
  - CHANGELOG updates
- [x] Contributors guide (#58)
  - Instructions/docs for installing `latest` from source
  - include `push -f` preference note
  - install `dev` deps
